# Generated by Django 5.1.3 on 2024-11-24 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

"""
Миграция для создания модели `ImageFeed`.

Эта миграция создаёт таблицу в базе данных для хранения информации
об изображениях, загруженных пользователями, включая обработанные версии
и результаты обработки.
"""

class Migration(migrations.Migration):

    # Указывает, что это начальная миграция для приложения
    initial = True

    # Зависимости: связываем модель с пользователем (AUTH_USER_MODEL)
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Операции для выполнения при применении миграции
    operations = [
        migrations.CreateModel(
            name='ImageFeed',
            fields=[
                # Поле ID (создаётся автоматически)
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),

                # Поле для загрузки исходного изображения
                ('image', models.ImageField(upload_to='images/')),

                # Поле для загрузки обработанного изображения
                ('processed_image', models.ImageField(
                    upload_to='processed_images/',
                    blank=True,
                    null=True
                )),

                # Поле для хранения текста результата обработки
                ('result', models.TextField(blank=True, null=True)),

                # Связь с моделью пользователя (ForeignKey)
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]