# Generated by Django 5.1.3 on 2024-11-27 11:06

from django.db import migrations, models

"""
Миграция для создания модели `ImageUpload`.

Эта миграция создаёт таблицу в базе данных для хранения информации
об изображениях, загружаемых пользователями, включая дату загрузки.
"""

class Migration(migrations.Migration):

    # Указываем зависимости: эта миграция зависит от начальной миграции приложения 'pusha'
    dependencies = [
        ('pusha', '0001_initial'),
    ]

    # Операции, выполняемые при миграции
    operations = [
        migrations.CreateModel(
            name='ImageUpload',  # Имя создаваемой модели
            fields=[
                # Поле ID (создаётся автоматически)
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),

                # Поле для загрузки изображения
                ('image', models.ImageField(upload_to='images/')),

                # Поле для автоматической записи даты и времени загрузки
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]