"""
Django settings for pupa project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

"""
Настройки Django проекта `pupa`.

Этот файл содержит настройки по умолчанию для разработки, включая
определение базовых путей, конфигурацию базы данных, установленные приложения,
middleware, обработку статических файлов и другие параметры.

Не используйте этот файл в production без соответствующей доработки!
"""

# Базовый путь проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# URL и директория для медиа-файлов
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Быстрая настройка для разработки
# Подробнее: https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Секретный ключ приложения
# Важно: В production храните секретный ключ в защищённом месте!
SECRET_KEY = 'django-insecure-hy9giv$t7$ookmzf=p-r&-^%q1&l_lrw&ti01npx6rzvdd98+1'

# Включение режима отладки
# Внимание: Убедитесь, что DEBUG=False в production!
DEBUG = True

# Список разрешённых хостов
ALLOWED_HOSTS = []

# Определение установленных приложений
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Локальное приложение
    'pusha',
]

# Список middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Основной модуль маршрутов
ROOT_URLCONF = 'pupa.urls'

# Настройки шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Настройка WSGI-приложения
WSGI_APPLICATION = 'pupa.wsgi.application'

# Конфигурация базы данных
# Подробнее: https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Валидация паролей
# Подробнее: https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Настройки интернационализации
# Подробнее: https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Настройка статических файлов (CSS, JavaScript, изображения)
# Подробнее: https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'

# Настройка типа первичного ключа по умолчанию
# Подробнее: https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL для перенаправления неавторизованных пользователей
# Убедитесь, что этот URL соответствует
LOGIN_REDIRECT_URL = '/dashboard/'